#!/usr/bin/env python3
import argparse
import concurrent.futures
import ipaddress
import json
import platform
import subprocess
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from enum import Enum
from pathlib import Path


class ScanStatus(str, Enum):
    IN_USE = "in_use"
    FREE = "free"


@dataclass
class ScanResult:
    name: str
    cidr: str
    description: str
    hosts_scanned: int
    in_use: list[str]
    free: list[str]
    conflicts: list[dict]
    missing: list[dict]
    untracked: list[str]

def render_report(results: list[ScanResult]) -> str:
    from collections import defaultdict
    from datetime import datetime

    grouped = defaultdict(list)

    for result in results:
        grouped[result.lab_name].append(result)

    lines = [
        "🚨 **IP Subnet Monitoring Report**",
        "==================================================",
        "",
    ]

    total_conflicts = 0
    total_missing = 0

    for lab_name, lab_results in grouped.items():

        lines.append(f"🏢 **{lab_name}**")
        lines.append("--------------------------------------------------")

        for result in lab_results:

            free_count = len(result.free)

            if free_count < 20:
                free_icon = "🔴"
            elif free_count < 50:
                free_icon = "🟡"
            else:
                free_icon = "🟢"

            lines.extend([
                f"📡 **{result.cidr}**",
                f"   ✅ Used IPs        : {len(result.in_use)}",
                f"   {free_icon} Free IPs        : {free_count}",
                f"   ❌ Conflicts       : {len(result.conflicts)}",
                f"   ⚠️ Missing         : {len(result.missing)}",
                ""
            ])

            total_conflicts += len(result.conflicts)
            total_missing += len(result.missing)

    lines.append("==================================================")
    lines.append("📢 ALERT SUMMARY")
    lines.append("==================================================")

    critical_subnets = []

    for result in results:
        if len(result.free) < 20:
            critical_subnets.append(
                f"🔴 {result.cidr} has only {len(result.free)} free IPs remaining."
            )

    if critical_subnets:
        lines.append("")
        lines.append("🚨 CRITICAL SUBNET ALERTS")
        lines.extend(critical_subnets)

    if total_conflicts:
        lines.append("")
        lines.append("🚨 DUPLICATE / CONFLICT IPs DETECTED")

        for result in results:
            for item in result.conflicts:
                lines.append(
                    f"❌ {item['ip']} expected=free actual={item['actual']}"
                )
    else:
        lines.append("")
        lines.append("✅ No duplicate/conflict IPs detected.")

    if total_missing:
        lines.append("")
        lines.append("⚠️ Missing expected in-use IPs:")

        for result in results:
            for item in result.missing:
                lines.append(
                    f"⚠️ {item['ip']} expected=in_use actual={item['actual']}"
                )

    lines.extend([
        "",
        f"⏰ Scan Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "🤖 Generated by Jenkins IP Subnet Monitor"
    ])

    return "\n".join(lines)
